name: Update Card Database

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '15 2 * * 0'  # At 02:15 UTC on Sunday

permissions:
  contents: write

concurrency:
  group: 'db-update'
  cancel-in-progress: true

jobs:
  db-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Read current version
        id: read_version
        run: |
          if [ -f db_version.txt ]; then
            old_version=$(cat db_version.txt)
          else
            old_version="n/a"
          fi
          echo "OLD_VERSION=$old_version" >> $GITHUB_ENV

      - name: Run the database update script
        run: npm run cardDbUpdate
        env:
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_BUCKET_NAME: ygo

      - name: Build
        run: npm run build

      - name: Read new version
        id: read_new_version
        run: |
          if [ -f db_version.txt ]; then
            new_version=$(cat db_version.txt)
          else
            new_version="n/a"
          fi
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet || echo "CHANGES_DETECTED=true" >> $GITHUB_ENV

      - name: Commit changes
        if: env.CHANGES_DETECTED == 'true'
        run: |
          git add db_version.txt src/assets/cards.en.json
          git commit -m "Update card database, ${{ env.OLD_VERSION }} -> ${{ env.NEW_VERSION }}"

      - name: Push changes
        if: env.CHANGES_DETECTED == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin master
